(deftheme c64
  "A C64-style custom theme.")

(let (
      (c64-black "#000000")
      (c64-white "#ffffff")
      (c64-red "#880000")
      (c64-cyan "#aaffee")
      (c64-violet "#cc44cc")
      (c64-green "#00cc55")
      (c64-blue "#0000aa")
      (c64-yellow "#eeee77")
      (c64-orange "#dd8855")
      (c64-brown "#664400")
      (c64-light-red "#ff7777")
      (c64-dark-grey "#333333")
      (c64-grey "#777777")
      (c64-light-green "#aaff66")
      (c64-light-blue "#0088ff")
      (c64-light-grey "#bbbbbb")))

(custom-theme-set-faces
 'c64
 '(default ((t (:family "default" :foundry "default" :width normal :height 1 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#ffffaf" :background "#303030" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#ffffaf"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#87af87"))))
 '(homoglyph ((t (:foreground "#ffaf00"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#afaf00" :background "#303030"))))
 '(highlight ((t (:foreground "#ffffaf" :background "#767676"))))
 '(region ((t (:background "#4e4e4e"))))
 '(shadow ((t (:foreground "#767676"))))
 '(secondary-selection ((t (:background "#3a3a3a"))))
 '(trailing-whitespace ((t (:background "#d75f5f"))))
 '(font-lock-builtin-face ((t (:foreground "#ff8700"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#767676"))))
 '(font-lock-constant-face ((t (:foreground "#d787af"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#ffaf00"))))
;; '(font-lock-keyword-face ((t (:foreground "#d75f5f"))))
 '(font-lock-keyword-face ((t (:foreground "#00ff00"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#00cc55"))))
 '(font-lock-type-face ((t (:foreground "#d787af"))))
 '(font-lock-variable-name-face ((t (:foreground "#87afaf"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#d75f5f"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#87afaf"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:background "#303030"))))
 '(header-line ((t (:box nil :foreground "#a8a8a8" :background "#262626" :inherit nil))))
 '(tooltip ((t (:foreground "#ffdfaf" :background "#3a3a3a"))))
 '(mode-line ((t (:box nil :foreground "#bcbcbc" :background "#626262"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#949494" :background "#3a3a3a"))))
 '(isearch ((t (:foreground "#000000" :background "#ff8700"))))
 '(isearch-fail ((t (:foreground "#ffffaf" :background "#d75f5f"))))
 '(lazy-highlight ((t (:foreground "#000000" :background "#ffaf00"))))
;; '(lazy-highlight ((t (:foreground ,c64-black :background "#ffaf00"))))
 '(match ((t (:foreground "#262626" :background "#87afaf"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'c64)
